name: Add bugs to triage project

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    name: Add issue to bug triage project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.6.1
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/orgs/test-organization-ca-scribner/projects/3
          github-token: ${{ secrets.PAT_FOR_ORG }}
          labeled: bug
          label-operator: OR
