name: Communication labeler

on:
  issue_comment:
    types: [created]

jobs:
  echo-stuff:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Github Context: ${{ github }}"
  identify-commenter:
    runs-on: ubuntu-latest
    outputs:
      team_member: ${{ steps.is-team-member.outputs.team_member }}
    steps:
    - id: is-team-member
      uses: morfien101/actions-authorized-user@v3
      with:
        # The username or list of usernames to check
        username: ${{ github.actor }}
        # The team name to check
        team: "team1"
        # The organization to check
        org: ${{ github.repository_owner }}
        # The github token to use. Must have at least 'org:read' scope.
        github_token: ${{ secrets.PAT_FOR_ORG }}
    - id: output-from-is-team-member
      run: |
        echo "output from team 1:"
        echo "authorized: ${{ steps.is-team-member.outputs.authorized }}"
        echo "team_member: ${{ steps.is-team-member.outputs.team_member }}"
  team-response:
    runs-on: ubuntu-latest
    needs: [identify-commenter]
    if: needs.identify-commenter.team_member == 'true'
    steps:
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: coms/needs-team-response
  reporter-response:
    runs-on: ubuntu-latest
    needs: [identify-commenter]
    if: needs.identify-commenter.team_member != 'true' && 
    steps:
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: coms/needs-team-response
