name: Communication labeler

on:
  issue_comment:
    types: [created]

jobs:
  echo-stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  



  identify-commenter:
    runs-on: ubuntu-latest
    outputs:
      team_member: ${{ steps.is-team-member.outputs.team_member }}
      is_reporter: ${{ steps.is-reporter.outputs.is_reporter }}
    steps:
    - id: is-team-member
      uses: morfien101/actions-authorized-user@v3
      with:
        # The username or list of usernames to check
        username: ${{ github.actor }}
        # The team name to check
        team: "team1"
        # The organization to check
        org: ${{ github.repository_owner }}
        # The github token to use. Must have at least 'org:read' scope.
        github_token: ${{ secrets.PAT_FOR_ORG }}
    - id: output-from-is-team-member
      run: |
        echo "output from team 1:"
        echo "authorized: ${{ steps.is-team-member.outputs.authorized }}"
        echo "team_member: ${{ steps.is-team-member.outputs.team_member }}"
    - id: is-reporter
      run: |
        echo "github.event.comment.user.login = ${{ github.event.comment.user.login }}"
        echo "github.event.issue.user.login = ${{ github.event.issue.user.login }}"
        IS_REPORTER="${{ github.event.comment.user.login == github.event.issue.user.login }}"
        echo "is_reporter=$IS_REPORTER"
        echo "{is_reporter}=$IS_REPORTER" >> "$GITHUB_OUTPUT"

  echo-identify-commenter:
    runs-on: ubuntu-latest
    needs: [identify-commenter]
    steps:
    - run: |
        echo needs.identify-commenter.team_member = ${{ needs.identify-commenter.team_member }}
        echo needs.identify-commenter.is_reporter = ${{ needs.identify-commenter.is_reporter }}

  team-response:
    runs-on: ubuntu-latest
    needs: [identify-commenter]
    if: needs.identify-commenter.team_member == 'true'
    steps:
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: coms/needs-team-response
  reporter-response:
    runs-on: ubuntu-latest
    needs: [identify-commenter]
    if: needs.identify-commenter.is_reporter == 'true'
    steps:
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: coms/needs-reporter-response
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: coms/needs-team-response
